name: appfurtos
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutter_modular: ^3.4.1+1
  flutter_triple: ^1.2.7+2
  update: ^0.3.1
  image_picker: 0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  triple_test: ^1.0.0
  flutter_modular_test: ^1.0.2

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/imagens/background_login.png
